version: 2.1
orbs:
  flutter: circleci/flutter@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
  android: circleci/android@2.1.2
filters: &filters
  tags:
    only: /.*/
jobs:
  integration-test-macos:
    macos:
      xcode: 14.2.0
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          app-dir: ./sample
      - flutter/install_ios_pod:
          app-dir: ./sample
      - flutter/install_ios_gem:
          app-dir: ./sample
      - run: 
          name: 'check that the sdk is installed properly'
          command: cd sample && flutter doctor && rbenv version
  integration-test-linux:
    executor:
      name: android/android-machine
      tag: '2022.09.1'
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          cache-version: v2
          app-dir: ./sample
      - flutter/install_android_gradle_dependencies:
          app-dir: ./sample
      - flutter/install_android_gem:
          app-dir: ./sample
      - run: 
          name: 'check that the sdk is installed properly'
          command: cd sample && flutter doctor && rvm version
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - integration-test-macos:
          filters: *filters
      - integration-test-linux:
          filters: *filters
      - flutter/unit_test:
          app-dir: ./sample
          registry: "ghcr.io/cirruslabs"
          version: "3.7.7"
          filters: *filters
      - flutter/lint:
          app-dir: ./sample
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: circleci/flutter
          vcs-type: << pipeline.project.type >>
          github-token: GHI_TOKEN
          pub-type: production
          requires:
            - orb-tools/pack
            - integration-test-macos
            - integration-test-linux
            - flutter/unit_test
            - flutter/lint
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
