version: 2.1
orbs:
  flutter: {}
  orb-tools: circleci/orb-tools@12.3.1
  android: circleci/android@3.1.0
parameters:
  cache_version:
    type: string
    default: v1.2
filters: &filters
  tags:
    only: /.*/
jobs:
  integration-test-macos:
    macos:
      xcode: 16.3.0
    resource_class: macos.m1.large.gen1
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          cache_version: <<pipeline.parameters.cache_version >>
          version: 3.32.7
          app_dir: ./sample
      - flutter/install_ios_pod:
          cache_version: <<pipeline.parameters.cache_version >>
          repo_update: true
          app_dir: ./sample
      - flutter/install_ios_gem:
          cache_version: <<pipeline.parameters.cache_version >>
          app_dir: ./sample
      - run:
          name: 'check that the sdk is installed properly'
          command: cd sample && flutter doctor && rbenv version
  integration-test-channel-beta:
    macos:
      xcode: 16.3.0
    resource_class: macos.m1.large.gen1
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          cache_version: <<pipeline.parameters.cache_version >>
          app_dir: ./sample
          channel: beta
          version: 3.27.0-0.1.pre
      - flutter/install_ios_pod:
          cache_version: <<pipeline.parameters.cache_version >>
          repo_update: true
          app_dir: ./sample
      - flutter/install_ios_gem:
          cache_version: <<pipeline.parameters.cache_version >>
          app_dir: ./sample
      - run:
          name: 'check that the sdk is installed properly from the beta channel'
          command: cd sample && flutter doctor && rbenv version
  integration-test-linux:
    executor:
      name: android/android_machine
      tag: '2024.11.1'
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: 3.32.7
          cache_version: <<pipeline.parameters.cache_version >>
          app_dir: ./sample
      - flutter/install_android_gradle_dependencies:
          cache_version: <<pipeline.parameters.cache_version >>
          app_dir: ./sample
      - flutter/install_android_gem:
          cache_version: <<pipeline.parameters.cache_version >>
          app_dir: ./sample
      - run:
          name: 'check that the sdk is installed properly'
          command: cd sample && flutter doctor
workflows:
  test-deploy:
    jobs:
      # Make sure to include "filters: *filters" in every test job you want to run as part of your deployment.
      - integration-test-macos:
          filters: *filters
      - integration-test-channel-beta:
          filters: *filters
      - integration-test-linux:
          filters: *filters
      - flutter/unit_test:
          cache_version: <<pipeline.parameters.cache_version >>
          app_dir: ./sample
          version: "3.32.7"
          filters: *filters
      - flutter/lint:
          version: 3.32.7
          cache_version: <<pipeline.parameters.cache_version >>
          app_dir: ./sample
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb_name: circleci/flutter
          vcs_type: << pipeline.project.type >>
          github_token: GHI_TOKEN
          pub_type: production
          requires:
            - orb-tools/pack
            - integration-test-macos
            - integration-test-linux
            - flutter/unit_test
            - flutter/lint
          context: orb-publisher
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
